// firebase_options.dart

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:io' show Platform;

/// A class that provides Firebase configuration options for different platforms.
/// This class is automatically generated by the FlutterFire CLI and contains
/// the necessary configuration details to initialize Firebase in your app.
class DefaultFirebaseOptions {
  /// Returns the appropriate Firebase configuration based on the current platform.
  /// This method automatically detects the platform (web, android, ios, etc.) and
  /// returns the corresponding Firebase configuration.
  ///
  /// Throws [UnsupportedError] if the platform is not supported or if the
  /// configuration for a specific platform hasn't been set up yet.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (Platform.operatingSystem) {
      case 'android':
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case 'ios':
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case 'macos':
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case 'windows':
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case 'linux':
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration for web platform.
  /// Contains the necessary API keys and configuration details for Firebase web.
  /// These values should be filled in with your actual Firebase project credentials.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "", // Your Firebase API key
    authDomain: "", // Your Firebase Auth domain
    projectId: "", // Your Firebase project ID
    storageBucket: "", // Your Firebase Storage bucket
    messagingSenderId: "", // Your Firebase Cloud Messaging sender ID
    appId: "", // Your Firebase app ID
  );
}
